#!/usr/bin/env bash
set -euo pipefail

INTENT="${1:?Usage: bootstrap.sh <intent> [output-dir]}"
OUTPUT_DIR="${2:-}"

echo "=== Meta-Harness Bootstrap ==="
echo ""

echo "[1/5] Interpreting intent..."
echo "  Raw intent: $INTENT"

TASK_NAME=$(echo "$INTENT" | sed 's/[^a-zA-Z0-9 ]//g' | sed 's/  */-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//' | tr '[:upper:]' '[:lower:]')
TASK_NAME=$(echo "$TASK_NAME" | cut -c1-50)

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="generated/$TASK_NAME"
fi

echo ""
echo "[2/5] Checking existing knowledge..."

if [ -f "memory/generation-log.md" ]; then
    PREV_COUNT=$(grep -c "## Generation" memory/generation-log.md 2>/dev/null || echo 0)
    echo "  Found $PREV_COUNT previous generations in log"
fi

if [ -f "memory/task-patterns.md" ]; then
    echo "  Task patterns available for reference"
fi

echo ""
echo "[3/5] Preparing output directory..."

mkdir -p "$OUTPUT_DIR/.agents/constraints" \
         "$OUTPUT_DIR/.agents/workflows" \
         "$OUTPUT_DIR/.agents/skills" \
         "$OUTPUT_DIR/scripts" \
         "$OUTPUT_DIR/config"

echo "  Created: $OUTPUT_DIR"

echo ""
echo "[4/5] Generating task definition..."

cat > "$OUTPUT_DIR/task-definition.md" << HEREDOC
# Task Definition (Auto-Generated)

## Raw Intent
$INTENT

## Status: PENDING INTERPRETATION

This task definition was auto-generated by bootstrap.sh.
An agent must now:
1. Read meta/interpreter.md and interpret the raw intent
2. Fill in the structured task definition below
3. Read meta/harness-generator.md and generate the harness
4. Read meta/agent-factory.md and create agent configurations
5. Read meta/orchestrator.md and plan execution

## Structured Task Definition (TO BE FILLED)
\`\`\`yaml
task:
  name: 
  domain: 
  goal: 
  scale: 
  quality_attributes: []
  hard_constraints: []
  soft_constraints: []
  unknowns: []
  template: 
  acceptance_criteria: []
  assumptions: []
\`\`\`
HEREDOC

echo "  Created: $OUTPUT_DIR/task-definition.md"

echo ""
echo "[5/5] Next Steps"
echo ""
echo "  The bootstrap has prepared the output directory and task definition."
echo "  An agent must now complete the compilation pipeline:"
echo ""
echo "  1. Read META.md for the full pipeline overview"
echo "  2. Read meta/interpreter.md and interpret the intent"
echo "  3. Fill in $OUTPUT_DIR/task-definition.md"
echo "  4. Read meta/harness-generator.md and generate the harness"
echo "  5. Read meta/agent-factory.md and create agent configs"
echo "  6. Read meta/orchestrator.md and plan execution"
echo "  7. Execute the plan with generated harness+agents"
echo ""
echo "  Output directory: $OUTPUT_DIR"
echo ""
echo "=== Bootstrap Complete ==="
